// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-8zfB2OA2NMfTqkZ4xRH2qFFJ5IjldM',
    appId: '1:891331476937:android:61d6bd77d7912049d23c18',
    messagingSenderId: '891331476937',
    projectId: 'com-health-shepherd',
    storageBucket: 'com-health-shepherd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlE-Yir-rNj8txdIEL-Y7wOeYzTH1tMlk',
    appId: '1:891331476937:ios:874902fecaafcac6d23c18',
    messagingSenderId: '891331476937',
    projectId: 'com-health-shepherd',
    storageBucket: 'com-health-shepherd.appspot.com',
    iosClientId: '891331476937-gvt1pq302uhaa0hqqmofaqv2kflvfst6.apps.googleusercontent.com',
    iosBundleId: 'com.pbj010dev.shepherd',
  );
}
